### PR TITLE
Template Logo Website

### PR DESCRIPTION
**Pull request by LuqmanHakim7**

### CODE REVIEW

**Comment by LuqmanHakim7** [comment]
I have donated a logo for your website, is it acceptable, please give your feedback

**Comment by mnosov622** [comment]
Hi @LuqmanHakim7 !

Thank you for contribution. I don't think that the name is fit for this project. Could you come up with something else, please ?

**Comment by LuqmanHakim7** [comment]
Can you explain your project description in detail so I can find a logo
philosophy that fits your project

Pada tanggal Jum, 14 Okt 2022 pukul 10.20 Maxim Nosov <
***@***.***> menulis:

**Comment by mnosov622** [comment]
Sorry, logo is changed

**Pull request closed without merging**
