### PR TITLE
Changed the logo

### PR DESCRIPTION
**Pull request by Divyesh1511**
Changed the logo of the website

### CODE REVIEW

**Comment by Divyesh1511** [comment]
Here is the screenshot of the website with the new logo
Screenshot (767)

**Comment by mnosov622** [comment]
Looks great !

Can you add text right next to the logo, please .

"To do planner" will be great. 

Add another style that you think would fit.

Thank you !

**Comment by Divyesh1511** [comment]
Ok I am trying to make it better

**Comment by Divyesh1511** [comment]
Screenshot (769)
Is this good or need any other changes?

**Comment by mnosov622** [comment]
Looks great !

Please make another commit here

**Comment by Divyesh1511** [comment]
Yes it's not going outside of navbar

**Comment by Divyesh1511** [comment]
You can have a look, I made commit

**Comment by mnosov622** [comment]
Thank you ! Looks good

**Pull request merged**
