### PR TITLE
Improved UI for mobile devices

### PR DESCRIPTION
**Pull request by ShailavMalik**
fixed issues #39 Date is collapsing into the Application logo and #35 Make application responsive with smaller layouts.
please check below attached screenshots.
<br>

screenshot in wide size screens

image

screenshot in mid-size screens with dark mode enabled

screencapture-127-0-0-1-5501-index-html-2022-10-27-17_35_09

screenshot in mobile screens

screencapture-127-0-0-1-5501-index-html-2022-10-27-17_34_07

### CODE REVIEW

**Comment by ShailavMalik** [comment]
@mnosov622 please review the PR for fix to #39 and let me know if any changes are required

**Comment by mnosov622** [comment]
Hi !

Please remove the color of the card and I will merge it :)
image

**Comment by ShailavMalik** [comment]
@mnosov622 Please check now - *removed the background of the card you specify*

Click to see the deploy preview
https://deploy-preview-61--todo-simplifier.netlify.app/

**Comment by mnosov622** [comment]
Thank you for contribution @ShailavMalik !

**Pull request merged**
