### PR TITLE
Add automatic dark/light mode

### PR DESCRIPTION
**Pull request by N0ahMC**

### CODE REVIEW

**Comment by N0ahMC** [comment]
@mnosov622 Merge conflicts solved for this PR and the other one

**Comment by mnosov622** [comment]
Thank you for your contribution!

Please change text color to white in light mode here
image

Then I will merge.

Thank you!

**Comment by N0ahMC** [comment]
> Thank you for your contribution!
> 
> Please change text color to white in light mode here image
> 
> Then I will merge.
> 
> Thank you!

done

**Comment by mnosov622** [comment]
Thank you ! 

Please file an issue about disappearing tasks after they are checked. Need to discuss that :)

Please remove the disappearing task for now and I will merge it :)

**Pull request closed without merging**
